### ISSUE TITLE
how to use with multiple image format options?

### ISSUE THREAD

**Issue by starchild** [sitelint/css-lazy-loading-background#1]
Hi,

Thank you for your code - I'm running the example as shown on codepen and it works great.

The question I have, is how do we deal with multiple formats?

eg if we're trying to satisfy google with a webp option,  how does this factor in?

`element.style {
    background: image-set(url(/thumb.jpg)1x) no-repeat center;
    background: url(/thumb.jpg.webp) no-repeat center;
    background: -webkit-image-set(url(/thumb.jpg.webp)1x) no-repeat center;
    background-size: cover;}
`
    
Thank you :)

**Comment by sitelint** [comment]
@starchild That is an interesting case. The challenge here is to determine which image will be loaded first. It's worth looking into further. In the meantime, any hints are welcome.

**Comment by starchild** [comment]
> @starchild That is an interesting case. The challenge here is to determine which image will be loaded first. It's worth looking into further. In the meantime, any hints are welcome.

The fallbacks should be in the same order as the above code. if the browser can't display webp, then the jpg shows

**Comment by sitelint** [comment]
> > @starchild That is an interesting case. The challenge here is to determine which image will be loaded first. It's worth looking into further. In the meantime, any hints are welcome.
> 
> The fallbacks should be in the same order as the above code. if the browser can't display webp, then the jpg shows

@starchild 

I think we could use following example code to determine if particular image is supported and start loading images based on the attribute `image-set` details:

```
function isImageSupported(mimeType) {
  const canvasElement = document.createElement('canvas');
  return canvasElement.toDataURL(mimeType).indexOf(`data:${mimeType}`) === 0;
}

const isPngSupported = isImageSupported('image/png');
```

**Comment by starchild** [comment]
don't you mean webp instead of png @sitelint  ?

**Comment by sitelint** [comment]
> don't you mean webp instead of png @sitelint ?

@starchild 
`webp` as well.

However, [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set) says:

> The image-set() function delivers the most appropriate image resolution for a user's device, providing a set of image options — each with an associated resolution declaration — from which the browser picks the most appropriate for the device and settings. 

From which "the browser picks the most appropriate for the device and settings" is most important here. The tricky part here is determining which image should be lazy loaded so that it matches the same behaviour as the browser does.

Sometimes the logic for selecting the image is a bit "unexpected". For example, when we set to use `png` and `webp` the browser selects `webp`, regardless of the image size. `webp` isn't always smaller than `png`, and for sure, the browser should know the size before fetching, but that would need to be specified at the code level, because otherwise it would require an extra HTTP request to determine image file size.

**Comment by starchild** [comment]
if it's the same image but converted to webp, then webp will always be smaller than png.  At least 99.99% of the time.  In fact, if we're serving a webp image, we should assume that this is the case, as this is the whole point of the exercise.

**Comment by sitelint** [comment]
> if it's the same image but converted to webp, then webp will always be smaller than png. At least 99.99% of the time. In fact, if we're serving a webp image, we should assume that this is the case, as this is the whole point of the exercise.

@starchild 
Agreed. I think this could be an initial step and be improved further in the future as needed.

**Comment by starchild** [comment]
fantastic @sitelint  :) Please let me know how I can help test this for you.

**Comment by sitelint** [comment]
@starchild Changes have been made to support the `image-set()` CSS functional notation. Repository has been updated and might be tested on following page:

https://www.sitelint.com/lab/css-background-lazy-loading/

**Comment by starchild** [comment]
I just can't get this to work locally. 

```
<style>
    .lazy-background-image-set {
        --background-image-set-lazy: image-lazy-set(url("/upload/artwork.jpg") 1x type("image/jpg"), url("/upload/artwork.webp") 1x type("image/webp"));
        background-image: var(--background-image-set-lazy);
    }
</style>
 <div class="is-overlay-bg lazy-background-image-set" style="background-size:cover">
 <script>
     (function () {
      const script = document.createElement('script');
      const head = document.head;

      script.src = '/resources/css-lazy-loading-background.js';
      script.type = 'text/javascript';
      script.async = true;

      script.onload = () => {
        const cssLazyLoadingBackground = new window['css-lazy-loading-background'].CssLazyLoadingBackground();

        cssLazyLoadingBackground.initialise();
      };

      head.insertBefore(script, head.firstChild);
    }());
</script>
```


What am I missing?  I also tried putting the js file contents in instead.

**Comment by sitelint** [comment]
@starchild  Can you create example code on https://jsfiddle.net/ or https://codepen.io/? That would help to debug the issue.

**Comment by starchild** [comment]
ty  anyway, but i just built one with GPT that works as I need it to, using modernizer.

Let me know if you'd like the code.

I appreciate your work though, thanks again.

**Comment by sitelint** [comment]
> ty anyway, but i just built one with GPT that works as I need it to, using modernizer.
> 
> Let me know if you'd like the code.
> 
> I appreciate your work though, thanks again.

If the created code works as expected, then that's all that matters. (y)

Still, the example that I've provided in one of my previous comments works fine.
